version: '3.5'
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-account
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    volumes:
      - psql-dados:/var/lib/postgresql/data
    restart: unless-stopped
  # APP*******************************************************************
  springbootapp:
    image: instant-account-interest-calculator:latest
    build: ./
    restart: always
    network_mode: bridge
    container_name: instant-account-interest-calculator
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  psql-dados:
